version: '3'

tasks:
  # =============================================================================
  # 初期化 — 依存ツールのインストールと環境変数ファイルのセットアップ
  # =============================================================================
  init:
    desc: Install pre-commit globally and set up git hooks
    cmds:
      - git config --local commit.template .commit-template
      - pipx install pre-commit
      - pre-commit install

  # =============================================================================
  # ビルド — ターゲットGemのビルドとCDN用のcanvas.txtの生成
  # =============================================================================
  build:gems:
    desc: Build target gem and generate CDN canvas.txt
    dir: dev
    cmds:
      - npm run build:gems

  # =============================================================================
  # lint — コードの整形とチェック
  # =============================================================================
  lint:
    desc: Lint code
    dir: dev
    cmds:
      - npm run lint
  